const FETCH_PROFILES_START = "FETCH_PROFILES_START";
const FETCH_PROFILES_SUCCESS = "FETCH_PROFILES_SUCCESS";
const FETCH_PROFILES_FAILURE = "FETCH_PROFILES_FAILURE";

export { FETCH_PROFILES_START, FETCH_PROFILES_SUCCESS, FETCH_PROFILES_FAILURE };
